# -*- coding: utf-8 -*-

"""
userapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from userapi.api_helper import APIHelper
from userapi.configuration import Server
from userapi.controllers.base_controller import BaseController


class TestController(BaseController):

    """A Controller to access Endpoints in the userapi API."""
    def __init__(self, config, auth_managers):
        super(TestController, self).__init__(config, auth_managers)

    def getuser(self):
        """Does a GET request to /api/users?page=1.

        TODO: type endpoint description here.

        Returns:
            string: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _url_path = '/api/users?page=1'
        _query_builder = self.config.get_base_uri()
        _query_builder += _url_path
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare and execute request
        _request = self.config.http_client.get(_query_url)
        # Apply authentication scheme on request
        self.apply_auth_schemes(_request, 'global')

        _response = self.execute_request(_request)
        self.validate_response(_response)

        decoded = _response.text

        return decoded
